Repository Savvy91/Update-hello.cpp, pull requests merged in 2021-10, with the labels that each got.

#12 Update Profile acc. to india
  update profile
Labels: bug, Hacktoberfest, hacktoberfest-accepted

#16 Update Android
  Android
Labels: bug, update, Hacktoberfest

#17 Update python
  python
Labels: bug, enhancement, good first issue, update, Hacktoberfest

#18 UPDATED
  IDEA code
Labels: enhancement, update, Hacktoberfest
